# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleardir < Formula
  desc "Clear empty directories and dispensable files."
  homepage "https://github.com/echocrow/cleardir"
  version "0.1.2"
  license "LGPL-3.0-or-later"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/cleardir/releases/download/v0.1.2/cleardir_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "7f2b764a077e64e40c2cdbcf67dfe663bdeefe44ee28db206c0863efef4498c6"

      def install
        bin.install "cleardir"
      end
    end
  end

  def caveats; <<~EOS
    By default cleardir will only clear fully empty directories.

    If you'd also like to clear certain files (e.g. ".DS_Store"), add them to
    the whitelist:
      echo -n '.DS_Store' > "$(cleardir --config '?')"
  EOS
  end

  test do
    system "#{bin}/cleardir", "--version"
  end
end
