# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleardir < Formula
  desc "Clear empty directories and dispensable files."
  homepage "https://github.com/echocrow/cleardir"
  version "0.1.0"
  license "LGPL-3.0-or-later"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/cleardir/releases/download/v0.1.0/cleardir_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "205d030fcdb2a537a7a037982b7b04d04fac95c42c095fe3e95efa2d02dd9b77"
    end
  end

  def install
    bin.install "cleardir"
  end

  def caveats; <<~EOS
    By default cleardir will only clear fully empty directories.

    If you'd also like to clear certain files (e.g. ".DS_Store"), add them to
    the whitelist:
      echo -n '.DS_Store' > "$(cleardir --config '?')"
  EOS
  end

  test do
    system "#{bin}/cleardir", "--version"
  end
end
