# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mouser < Formula
  desc "Automate actions via mouse gestures."
  homepage "https://github.com/echocrow/Mouser"
  version "1.2.2"
  license "LGPL-3.0-or-later"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/echocrow/Mouser/releases/download/v1.2.2/mouser_1.2.2_Darwin_x86_64.tar.gz"
    sha256 "cc1927cc5350291f71deb3e3b93946ce4fa861ce7832dc1aee57f6dcd369c2bb"
  end

  def install
    bin.install "mouser"
  end

  def caveats; <<~EOS
    To configure and run mouser, create and edit the config file:
      mkdir -p ~/.config/mouser && touch ~/.config/mouser/config.yml

    For examples on how to configure mouser, refer to the homepage:
      #{homepage}

    Note: The first time you run mouser you may need to provide additional
    permissions to the app:
      System Perferences > Security & Privacy > Privacy > Accessibility > mouser
    Once granted, restart mouser.
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>#{plist_name}</string>
  <key>ProgramArguments</key>
  <array>
    <string>#{bin}/mouser</string>
  </array>
  <key>RunAtLoad</key>
  <true />
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
</dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/mouser", "--version"
  end
end
