# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mouser < Formula
  desc "Automate actions via mouse gestures."
  homepage "https://github.com/echocrow/Mouser"
  version "1.4.3"
  license "LGPL-3.0-or-later"
  depends_on :macos

  on_macos do
    url "https://github.com/echocrow/Mouser/releases/download/v1.4.3/mouser_1.4.3_darwin_amd64.tar.gz"
    sha256 "c9788efe93d8b68067bede8d263f95444043d8db4a030d6f33fe248905220404"

    def install
      bin.install "mouser"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mouser
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      To configure and run mouser, create and edit the config file:
        mkdir -p "$(dirname "$(./mouser --config '?')")" && touch "$(./mouser --config '?')" && echo $_

      For examples on how to configure mouser, refer to the homepage:
        #{homepage}

      Note: The first time you run mouser you may need to provide additional
      permissions to the app:
        System Perferences > Security & Privacy > Privacy > Accessibility > mouser
      Once granted, restart mouser.
    EOS
  end

  service do
    run [opt_bin/"mouser"]
    run_at_load true
    keep_alive crashed: true
  end

  test do
    system "#{bin}/mouser --version"
  end
end
