# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pasteword < Formula
  desc "Paste basic or template-based keys and passwords."
  homepage "https://github.com/echocrow/pasteword"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/pasteword/releases/download/v0.1.0/pasteword_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d13345d0cb534b64fd832833262e97f18059fb9457d98ad3548f97a131b6d380"

      def install
        bin.install "pasteword"
      end
    end
  end

  test do
    system "#{bin}/pasteword", "-version"
  end
end
