# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pasteword < Formula
  desc "Paste basic or template-based keys and passwords."
  homepage "https://github.com/echocrow/pasteword"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/pasteword/releases/download/v0.2.0/pasteword_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "64207c6f55d80f5f04607eb22d451929c9e8f90336b0f80ec7b79ee2afb4d217"

      def install
        bin.install "pasteword"
      end
    end
  end

  test do
    system "#{bin}/pasteword", "-version"
  end
end
