# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unboot < Formula
  desc "A simple CLI to shutdown or restart macOS."
  homepage "https://github.com/echocrow/macos-unboot"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/macos-unboot/releases/download/v0.1.0/unboot_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "3cf9f827a9252440864729146e30e391a28d1280dec2c587e6b1a3b5ae9fad8c"

      def install
        bin.install "unboot"
      end
    end
  end

  test do
    system "#{bin}/unboot", "-version"
  end
end
