# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unix < Formula
  desc "A simple UNIX timestamp and date converter."
  homepage "https://github.com/echocrow/unix"
  version "1.0.2"
  license "LGPL-3.0-or-later"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/unix/releases/download/v1.0.2/unix_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "649ce7990a3a2cb898265cb687c6fb9344baed2ddb2db45a4c6de10685ccd668"

      def install
        bin.install "unix"
      end
    end
  end

  test do
    system "#{bin}/unix", "--version"
  end
end
