# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unix < Formula
  desc "A simple UNIX timestamp and date converter."
  homepage "https://github.com/echocrow/unix"
  version "1.0.0"
  license "LGPL-3.0-or-later"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/unix/releases/download/1.0.0/unix_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "df5d5ca11e06097e9195b919841e9f72600dfffdda52bccf04775088529844ae"
    end
  end

  def install
    bin.install "unix"
  end

  test do
    system "#{bin}/unix", "--version"
  end
end
