# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unix < Formula
  desc "A simple UNIX timestamp and date converter."
  homepage "https://github.com/echocrow/unix"
  version "1.0.1"
  license "LGPL-3.0-or-later"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/echocrow/unix/releases/download/1.0.1/unix_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "7df96c90d7229293cb79622128e3eb2a266c1e54bd0d49980a838afef3255082"
    end
  end

  def install
    bin.install "unix"
  end

  test do
    system "#{bin}/unix", "--version"
  end
end
